import java.util.scanner;
public class GameTest
{
    //main class to execute our program
    public static void main(String[] args)
    {
    Scanner scanner = new Scanner(System.in);
    // what the user will see when asked 
    System.out.println("What movie-category hangman game would you like to play?");
    System.out.println("Press 1 for Action Genre: ");
    System.out.println("Press 2 for Comedy Genre: ");
    System.out.println("Press 3 for Animated Genre: ");
    
    int userselection = scanner.nextInt();

    }

}